const DEFAULT_COLOR: string = '#0057e7';
const DEFAULT_BORDER_COLOR: string = "#0057e7";
const DEFAULT_WIDTH: number = 150;
const DEFAULT_HEIGHT: number = 6;
const DEFAULT_BORDER_RADIUS: number = 4;
const DEFAULT_BORDER_WIDTH: number = 1;
export {
    DEFAULT_COLOR,
    DEFAULT_WIDTH,
    DEFAULT_HEIGHT,
    DEFAULT_BORDER_RADIUS,
    DEFAULT_BORDER_COLOR,
    DEFAULT_BORDER_WIDTH
}